# Travis CI (https://travis-ci.org/)

language: c
dist: bionic
cache:
  apt: true # only works with Pro version

env:
  global:
    - OCTFLAGS="--no-gui --no-window-system --silent"

before_install:
  - travis_retry sudo apt-get -y -qq update
  - travis_retry sudo apt-get -y install octave
  - travis_retry sudo apt-get -y install liboctave-dev
  - travis_retry sudo apt-get -y install nodejs
  - travis_retry sudo apt-get -y install npm
  - cd .. && git clone https://github.com/florianschanda/miss_hit.git && export PATH=$PATH:`pwd`/miss_hit && cd CPP_BIDS


install:
  # Install JSONio
  #- travis_retry git clone git://github.com/gllmflndn/JSONio.git --depth 1
  - cd lib/JSONio; mkoctfile --mex jsonread.c jsmn.c -DJSMN_PARENT_LINKS; cd ../..
  #- octave $OCTFLAGS --eval "addpath (fullfile (pwd, 'JSONio')); savepath ();"
  # Install BIDS-MATLAB
  - octave $OCTFLAGS --eval "addpath (pwd); savepath ();"
  # Install BIDS-Validator
  - sudo npm install -g bids-validator

before_script:
  # Change current directory
  - cd tests

jobs:
  include:
    - stage: "Tests and linter"
      name: "Unit Tests" # names the first job
      script: octave $OCTFLAGS --eval "results = runTests; assert(all(~[results.Failed]))"
    - script: cd .. && mh_style `pwd`
      name: "miss_hit linter" # names the second job
    - stage: "BIDS validator"
      name: "create and check dataset" # names the second job
    - script: octave $OCTFLAGS --eval "makeRawDataset_test" && bids-validator `pwd`/../output/rawdata/ --ignoreNiftiHeaders
    